//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::vec_init_then_push)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;
use trident_fuzz::AccountDiscriminator;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: dead_man_switch
// ----------------------------------------------------------------------------
pub mod dead_man_switch {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for dead_man_switch
    pub fn program_id() -> Pubkey {
        pubkey!("9tfSr7zg9bGBfpSqqdwCACiSfAqsbdE4rNnwezFe5Ldm")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: CheckIn
    // ....................................................................

    /// Main instruction struct for CheckIn
    pub struct CheckInInstruction {
        pub accounts: CheckInInstructionAccountMetas,
        pub data: CheckInInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CheckIn instruction
    #[derive(Debug, Clone, Default)]
    pub struct CheckInInstructionAccountMetas {
        pub owner: AccountMeta,

        pub vault: AccountMeta,
    }

    /// Account pubkeys for CheckIn instruction
    #[derive(Debug, Clone)]
    pub struct CheckInInstructionAccounts {
        pub owner: Pubkey,

        pub vault: Pubkey,
    }

    impl CheckInInstructionAccounts {
        pub fn new(owner: Pubkey, vault: Pubkey) -> Self {
            Self { owner, vault }
        }
    }

    /// Instruction data for CheckIn
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CheckInInstructionData {}

    impl CheckInInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CheckInInstruction
    impl CheckInInstruction {
        fn discriminator() -> [u8; 8] {
            [209u8, 253u8, 4u8, 217u8, 250u8, 241u8, 207u8, 50u8]
        }

        pub fn data(data: CheckInInstructionData) -> Self {
            Self {
                accounts: CheckInInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CheckInInstructionAccounts) -> Self {
            self.accounts.owner = AccountMeta::new_readonly(accounts.owner, true);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.owner.clone());

            metas.push(self.accounts.vault.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ClaimSol
    // ....................................................................

    /// Main instruction struct for ClaimSol
    pub struct ClaimSolInstruction {
        pub accounts: ClaimSolInstructionAccountMetas,
        pub data: ClaimSolInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ClaimSol instruction
    #[derive(Debug, Clone, Default)]
    pub struct ClaimSolInstructionAccountMetas {
        pub beneficiary: AccountMeta,

        pub vault: AccountMeta,
    }

    /// Account pubkeys for ClaimSol instruction
    #[derive(Debug, Clone)]
    pub struct ClaimSolInstructionAccounts {
        pub beneficiary: Pubkey,

        pub vault: Pubkey,
    }

    impl ClaimSolInstructionAccounts {
        pub fn new(beneficiary: Pubkey, vault: Pubkey) -> Self {
            Self { beneficiary, vault }
        }
    }

    /// Instruction data for ClaimSol
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ClaimSolInstructionData {}

    impl ClaimSolInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for ClaimSolInstruction
    impl ClaimSolInstruction {
        fn discriminator() -> [u8; 8] {
            [139u8, 113u8, 179u8, 189u8, 190u8, 30u8, 132u8, 195u8]
        }

        pub fn data(data: ClaimSolInstructionData) -> Self {
            Self {
                accounts: ClaimSolInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ClaimSolInstructionAccounts) -> Self {
            self.accounts.beneficiary = AccountMeta::new(accounts.beneficiary, true);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.beneficiary.clone());

            metas.push(self.accounts.vault.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ClaimSpl
    // ....................................................................

    /// Main instruction struct for ClaimSpl
    pub struct ClaimSplInstruction {
        pub accounts: ClaimSplInstructionAccountMetas,
        pub data: ClaimSplInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ClaimSpl instruction
    #[derive(Debug, Clone, Default)]
    pub struct ClaimSplInstructionAccountMetas {
        pub beneficiary: AccountMeta,

        pub vault: AccountMeta,

        pub mint: AccountMeta,

        pub vault_token_account: AccountMeta,

        pub beneficiary_token_account: AccountMeta,

        pub token_program: AccountMeta,

        pub associated_token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for ClaimSpl instruction
    #[derive(Debug, Clone)]
    pub struct ClaimSplInstructionAccounts {
        pub beneficiary: Pubkey,

        pub vault: Pubkey,

        pub mint: Pubkey,

        pub vault_token_account: Pubkey,

        pub beneficiary_token_account: Pubkey,

        pub token_program: Pubkey,
    }

    impl ClaimSplInstructionAccounts {
        pub fn new(
            beneficiary: Pubkey,

            vault: Pubkey,

            mint: Pubkey,

            vault_token_account: Pubkey,

            beneficiary_token_account: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                beneficiary,

                vault,

                mint,

                vault_token_account,

                beneficiary_token_account,

                token_program,
            }
        }
    }

    /// Instruction data for ClaimSpl
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ClaimSplInstructionData {}

    impl ClaimSplInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for ClaimSplInstruction
    impl ClaimSplInstruction {
        fn discriminator() -> [u8; 8] {
            [178u8, 141u8, 219u8, 41u8, 138u8, 211u8, 162u8, 60u8]
        }

        pub fn data(data: ClaimSplInstructionData) -> Self {
            Self {
                accounts: ClaimSplInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ClaimSplInstructionAccounts) -> Self {
            self.accounts.beneficiary = AccountMeta::new(accounts.beneficiary, true);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.vault_token_account =
                AccountMeta::new(accounts.vault_token_account, false);

            self.accounts.beneficiary_token_account =
                AccountMeta::new(accounts.beneficiary_token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.beneficiary.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.vault_token_account.clone());

            metas.push(self.accounts.beneficiary_token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CloseVault
    // ....................................................................

    /// Main instruction struct for CloseVault
    pub struct CloseVaultInstruction {
        pub accounts: CloseVaultInstructionAccountMetas,
        pub data: CloseVaultInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CloseVault instruction
    #[derive(Debug, Clone, Default)]
    pub struct CloseVaultInstructionAccountMetas {
        pub owner: AccountMeta,

        pub vault: AccountMeta,

        pub vault_token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for CloseVault instruction
    #[derive(Debug, Clone)]
    pub struct CloseVaultInstructionAccounts {
        pub owner: Pubkey,

        pub vault: Pubkey,

        pub vault_token_account: Pubkey,

        pub token_program: Pubkey,
    }

    impl CloseVaultInstructionAccounts {
        pub fn new(
            owner: Pubkey,

            vault: Pubkey,

            vault_token_account: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                owner,

                vault,

                vault_token_account,

                token_program,
            }
        }
    }

    /// Instruction data for CloseVault
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CloseVaultInstructionData {}

    impl CloseVaultInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CloseVaultInstruction
    impl CloseVaultInstruction {
        fn discriminator() -> [u8; 8] {
            [141u8, 103u8, 17u8, 126u8, 72u8, 75u8, 29u8, 29u8]
        }

        pub fn data(data: CloseVaultInstructionData) -> Self {
            Self {
                accounts: CloseVaultInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CloseVaultInstructionAccounts) -> Self {
            self.accounts.owner = AccountMeta::new(accounts.owner, true);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.vault_token_account =
                AccountMeta::new(accounts.vault_token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.owner.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.vault_token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: DepositSol
    // ....................................................................

    /// Main instruction struct for DepositSol
    pub struct DepositSolInstruction {
        pub accounts: DepositSolInstructionAccountMetas,
        pub data: DepositSolInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for DepositSol instruction
    #[derive(Debug, Clone, Default)]
    pub struct DepositSolInstructionAccountMetas {
        pub owner: AccountMeta,

        pub vault: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for DepositSol instruction
    #[derive(Debug, Clone)]
    pub struct DepositSolInstructionAccounts {
        pub owner: Pubkey,

        pub vault: Pubkey,
    }

    impl DepositSolInstructionAccounts {
        pub fn new(owner: Pubkey, vault: Pubkey) -> Self {
            Self { owner, vault }
        }
    }

    /// Instruction data for DepositSol
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct DepositSolInstructionData {
        pub amount: u64,
    }

    impl DepositSolInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for DepositSolInstruction
    impl DepositSolInstruction {
        fn discriminator() -> [u8; 8] {
            [108u8, 81u8, 78u8, 117u8, 125u8, 155u8, 56u8, 200u8]
        }

        pub fn data(data: DepositSolInstructionData) -> Self {
            Self {
                accounts: DepositSolInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: DepositSolInstructionAccounts) -> Self {
            self.accounts.owner = AccountMeta::new(accounts.owner, true);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.owner.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: DepositSpl
    // ....................................................................

    /// Main instruction struct for DepositSpl
    pub struct DepositSplInstruction {
        pub accounts: DepositSplInstructionAccountMetas,
        pub data: DepositSplInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for DepositSpl instruction
    #[derive(Debug, Clone, Default)]
    pub struct DepositSplInstructionAccountMetas {
        pub owner: AccountMeta,

        pub vault: AccountMeta,

        pub mint: AccountMeta,

        pub owner_token_account: AccountMeta,

        pub vault_token_account: AccountMeta,

        pub token_program: AccountMeta,

        pub associated_token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for DepositSpl instruction
    #[derive(Debug, Clone)]
    pub struct DepositSplInstructionAccounts {
        pub owner: Pubkey,

        pub vault: Pubkey,

        pub mint: Pubkey,

        pub owner_token_account: Pubkey,

        pub vault_token_account: Pubkey,

        pub token_program: Pubkey,
    }

    impl DepositSplInstructionAccounts {
        pub fn new(
            owner: Pubkey,

            vault: Pubkey,

            mint: Pubkey,

            owner_token_account: Pubkey,

            vault_token_account: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                owner,

                vault,

                mint,

                owner_token_account,

                vault_token_account,

                token_program,
            }
        }
    }

    /// Instruction data for DepositSpl
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct DepositSplInstructionData {
        pub amount: u64,
    }

    impl DepositSplInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for DepositSplInstruction
    impl DepositSplInstruction {
        fn discriminator() -> [u8; 8] {
            [224u8, 0u8, 198u8, 175u8, 198u8, 47u8, 105u8, 204u8]
        }

        pub fn data(data: DepositSplInstructionData) -> Self {
            Self {
                accounts: DepositSplInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: DepositSplInstructionAccounts) -> Self {
            self.accounts.owner = AccountMeta::new(accounts.owner, true);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.owner_token_account =
                AccountMeta::new(accounts.owner_token_account, false);

            self.accounts.vault_token_account =
                AccountMeta::new(accounts.vault_token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.owner.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.owner_token_account.clone());

            metas.push(self.accounts.vault_token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: InitializeVault
    // ....................................................................

    /// Main instruction struct for InitializeVault
    pub struct InitializeVaultInstruction {
        pub accounts: InitializeVaultInstructionAccountMetas,
        pub data: InitializeVaultInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitializeVault instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeVaultInstructionAccountMetas {
        pub owner: AccountMeta,

        pub vault: AccountMeta,

        pub mint: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitializeVault instruction
    #[derive(Debug, Clone)]
    pub struct InitializeVaultInstructionAccounts {
        pub owner: Pubkey,

        pub vault: Pubkey,

        pub mint: Pubkey,
    }

    impl InitializeVaultInstructionAccounts {
        pub fn new(owner: Pubkey, vault: Pubkey, mint: Pubkey) -> Self {
            Self { owner, vault, mint }
        }
    }

    /// Instruction data for InitializeVault
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeVaultInstructionData {
        pub vault_id: u64,

        pub timeout_seconds: i64,

        pub beneficiaries: Vec<BeneficiaryInput>,
    }

    impl InitializeVaultInstructionData {
        pub fn new(
            vault_id: u64,

            timeout_seconds: i64,

            beneficiaries: Vec<BeneficiaryInput>,
        ) -> Self {
            Self {
                vault_id,

                timeout_seconds,

                beneficiaries,
            }
        }
    }

    /// Implementation for InitializeVaultInstruction
    impl InitializeVaultInstruction {
        fn discriminator() -> [u8; 8] {
            [48u8, 191u8, 163u8, 44u8, 71u8, 129u8, 63u8, 164u8]
        }

        pub fn data(data: InitializeVaultInstructionData) -> Self {
            Self {
                accounts: InitializeVaultInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeVaultInstructionAccounts) -> Self {
            self.accounts.owner = AccountMeta::new(accounts.owner, true);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.owner.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SetBeneficiaries
    // ....................................................................

    /// Main instruction struct for SetBeneficiaries
    pub struct SetBeneficiariesInstruction {
        pub accounts: SetBeneficiariesInstructionAccountMetas,
        pub data: SetBeneficiariesInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SetBeneficiaries instruction
    #[derive(Debug, Clone, Default)]
    pub struct SetBeneficiariesInstructionAccountMetas {
        pub owner: AccountMeta,

        pub vault: AccountMeta,
    }

    /// Account pubkeys for SetBeneficiaries instruction
    #[derive(Debug, Clone)]
    pub struct SetBeneficiariesInstructionAccounts {
        pub owner: Pubkey,

        pub vault: Pubkey,
    }

    impl SetBeneficiariesInstructionAccounts {
        pub fn new(owner: Pubkey, vault: Pubkey) -> Self {
            Self { owner, vault }
        }
    }

    /// Instruction data for SetBeneficiaries
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SetBeneficiariesInstructionData {
        pub beneficiaries: Vec<BeneficiaryInput>,
    }

    impl SetBeneficiariesInstructionData {
        pub fn new(beneficiaries: Vec<BeneficiaryInput>) -> Self {
            Self { beneficiaries }
        }
    }

    /// Implementation for SetBeneficiariesInstruction
    impl SetBeneficiariesInstruction {
        fn discriminator() -> [u8; 8] {
            [88u8, 248u8, 62u8, 255u8, 211u8, 46u8, 228u8, 130u8]
        }

        pub fn data(data: SetBeneficiariesInstructionData) -> Self {
            Self {
                accounts: SetBeneficiariesInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SetBeneficiariesInstructionAccounts) -> Self {
            self.accounts.owner = AccountMeta::new_readonly(accounts.owner, true);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.owner.clone());

            metas.push(self.accounts.vault.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: WithdrawSol
    // ....................................................................

    /// Main instruction struct for WithdrawSol
    pub struct WithdrawSolInstruction {
        pub accounts: WithdrawSolInstructionAccountMetas,
        pub data: WithdrawSolInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for WithdrawSol instruction
    #[derive(Debug, Clone, Default)]
    pub struct WithdrawSolInstructionAccountMetas {
        pub owner: AccountMeta,

        pub vault: AccountMeta,
    }

    /// Account pubkeys for WithdrawSol instruction
    #[derive(Debug, Clone)]
    pub struct WithdrawSolInstructionAccounts {
        pub owner: Pubkey,

        pub vault: Pubkey,
    }

    impl WithdrawSolInstructionAccounts {
        pub fn new(owner: Pubkey, vault: Pubkey) -> Self {
            Self { owner, vault }
        }
    }

    /// Instruction data for WithdrawSol
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct WithdrawSolInstructionData {
        pub amount: u64,
    }

    impl WithdrawSolInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for WithdrawSolInstruction
    impl WithdrawSolInstruction {
        fn discriminator() -> [u8; 8] {
            [145u8, 131u8, 74u8, 136u8, 65u8, 137u8, 42u8, 38u8]
        }

        pub fn data(data: WithdrawSolInstructionData) -> Self {
            Self {
                accounts: WithdrawSolInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: WithdrawSolInstructionAccounts) -> Self {
            self.accounts.owner = AccountMeta::new(accounts.owner, true);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.owner.clone());

            metas.push(self.accounts.vault.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: WithdrawSpl
    // ....................................................................

    /// Main instruction struct for WithdrawSpl
    pub struct WithdrawSplInstruction {
        pub accounts: WithdrawSplInstructionAccountMetas,
        pub data: WithdrawSplInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for WithdrawSpl instruction
    #[derive(Debug, Clone, Default)]
    pub struct WithdrawSplInstructionAccountMetas {
        pub owner: AccountMeta,

        pub vault: AccountMeta,

        pub mint: AccountMeta,

        pub vault_token_account: AccountMeta,

        pub owner_token_account: AccountMeta,

        pub token_program: AccountMeta,

        pub associated_token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for WithdrawSpl instruction
    #[derive(Debug, Clone)]
    pub struct WithdrawSplInstructionAccounts {
        pub owner: Pubkey,

        pub vault: Pubkey,

        pub mint: Pubkey,

        pub vault_token_account: Pubkey,

        pub owner_token_account: Pubkey,

        pub token_program: Pubkey,
    }

    impl WithdrawSplInstructionAccounts {
        pub fn new(
            owner: Pubkey,

            vault: Pubkey,

            mint: Pubkey,

            vault_token_account: Pubkey,

            owner_token_account: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                owner,

                vault,

                mint,

                vault_token_account,

                owner_token_account,

                token_program,
            }
        }
    }

    /// Instruction data for WithdrawSpl
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct WithdrawSplInstructionData {
        pub amount: u64,
    }

    impl WithdrawSplInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for WithdrawSplInstruction
    impl WithdrawSplInstruction {
        fn discriminator() -> [u8; 8] {
            [181u8, 154u8, 94u8, 86u8, 62u8, 115u8, 6u8, 186u8]
        }

        pub fn data(data: WithdrawSplInstructionData) -> Self {
            Self {
                accounts: WithdrawSplInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: WithdrawSplInstructionAccounts) -> Self {
            self.accounts.owner = AccountMeta::new(accounts.owner, true);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.vault_token_account =
                AccountMeta::new(accounts.vault_token_account, false);

            self.accounts.owner_token_account =
                AccountMeta::new(accounts.owner_token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.owner.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.vault_token_account.clone());

            metas.push(self.accounts.owner_token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Data Accounts (with discriminators)
    // ------------------------------------------------------------------------

    /// AccountDiscriminator implementation for Vault
    impl AccountDiscriminator for Vault {
        fn discriminator() -> &'static [u8] {
            &[211u8, 8u8, 232u8, 43u8, 2u8, 152u8, 117u8, 119u8]
        }
    }

    // ------------------------------------------------------------------------
    // Errors
    // ------------------------------------------------------------------------

    /// Program errors for dead_man_switch
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    #[repr(u32)]
    pub enum DeadmanswitchError {
        /// Signer is neither the vault owner nor a listed beneficiary
        Unauthorized = 6000,

        /// The inactivity timeout has not elapsed yet
        TimeoutNotReached = 6001,

        /// This beneficiary has already claimed their share
        AlreadyClaimed = 6002,

        /// Beneficiary shares must add up to exactly 10000 basis points
        InvalidShares = 6003,

        /// A vault can hold at most 5 beneficiaries
        TooManyBeneficiaries = 6004,

        /// Arithmetic overflow
        MathOverflow = 6005,

        /// Timeout must be between 60 seconds and 10 years
        InvalidTimeout = 6006,

        /// A vault needs at least one beneficiary
        NoBeneficiaries = 6007,

        /// The same wallet is listed as a beneficiary twice
        DuplicateBeneficiary = 6008,

        /// Beneficiary address must not be the default pubkey
        InvalidBeneficiary = 6009,

        /// Amount must be greater than zero
        InvalidAmount = 6010,

        /// Mint does not match the one this vault was created for
        MintMismatch = 6011,

        /// This instruction is only valid for a native SOL vault
        NotSolVault = 6012,

        /// This instruction is only valid for an SPL token vault
        NotSplVault = 6013,

        /// The switch has already tripped; the owner can no longer change the
        /// vault
        VaultTriggered = 6014,

        /// Vault balance is too low for this operation
        InsufficientFunds = 6015,

        /// A vault must be empty before it can be closed
        VaultNotEmpty = 6016,

        /// An SPL vault needs its token account and token program passed in
        MissingTokenAccount = 6017,
    }

    impl DeadmanswitchError {
        /// Get the error code
        pub fn code(&self) -> u32 {
            *self as u32
        }

        /// Get the error message
        pub fn msg(&self) -> &'static str {
            match self {
                Self::Unauthorized => "Signer is neither the vault owner nor a listed beneficiary",

                Self::TimeoutNotReached => "The inactivity timeout has not elapsed yet",

                Self::AlreadyClaimed => "This beneficiary has already claimed their share",

                Self::InvalidShares => {
                    "Beneficiary shares must add up to exactly 10000 basis points"
                }

                Self::TooManyBeneficiaries => "A vault can hold at most 5 beneficiaries",

                Self::MathOverflow => "Arithmetic overflow",

                Self::InvalidTimeout => "Timeout must be between 60 seconds and 10 years",

                Self::NoBeneficiaries => "A vault needs at least one beneficiary",

                Self::DuplicateBeneficiary => "The same wallet is listed as a beneficiary twice",

                Self::InvalidBeneficiary => "Beneficiary address must not be the default pubkey",

                Self::InvalidAmount => "Amount must be greater than zero",

                Self::MintMismatch => "Mint does not match the one this vault was created for",

                Self::NotSolVault => "This instruction is only valid for a native SOL vault",

                Self::NotSplVault => "This instruction is only valid for an SPL token vault",

                Self::VaultTriggered => {
                    "The switch has already tripped; the owner can no longer change the vault"
                }

                Self::InsufficientFunds => "Vault balance is too low for this operation",

                Self::VaultNotEmpty => "A vault must be empty before it can be closed",

                Self::MissingTokenAccount => {
                    "An SPL vault needs its token account and token program passed in"
                }
            }
        }

        /// Try to convert from error code
        pub fn from_code(code: u32) -> Option<Self> {
            match code {
                6000 => Some(Self::Unauthorized),

                6001 => Some(Self::TimeoutNotReached),

                6002 => Some(Self::AlreadyClaimed),

                6003 => Some(Self::InvalidShares),

                6004 => Some(Self::TooManyBeneficiaries),

                6005 => Some(Self::MathOverflow),

                6006 => Some(Self::InvalidTimeout),

                6007 => Some(Self::NoBeneficiaries),

                6008 => Some(Self::DuplicateBeneficiary),

                6009 => Some(Self::InvalidBeneficiary),

                6010 => Some(Self::InvalidAmount),

                6011 => Some(Self::MintMismatch),

                6012 => Some(Self::NotSolVault),

                6013 => Some(Self::NotSplVault),

                6014 => Some(Self::VaultTriggered),

                6015 => Some(Self::InsufficientFunds),

                6016 => Some(Self::VaultNotEmpty),

                6017 => Some(Self::MissingTokenAccount),

                _ => None,
            }
        }
    }

    impl std::fmt::Display for DeadmanswitchError {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{}: {}", self.code(), self.msg())
        }
    }

    impl std::error::Error for DeadmanswitchError {}

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------

    // ------------------------------------------------------------------------
    // Custom Types
    // ------------------------------------------------------------------------

    /// Custom struct: Beneficiary
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct Beneficiary {
        pub address: Pubkey,

        pub share_bps: u16,

        pub claimed: bool,
    }

    impl Beneficiary {
        pub fn new(address: Pubkey, share_bps: u16, claimed: bool) -> Self {
            Self {
                address,

                share_bps,

                claimed,
            }
        }
    }

    /// Custom struct: BeneficiaryInput
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct BeneficiaryInput {
        pub address: Pubkey,

        pub share_bps: u16,
    }

    impl BeneficiaryInput {
        pub fn new(address: Pubkey, share_bps: u16) -> Self {
            Self { address, share_bps }
        }
    }

    /// Custom struct: Vault
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct Vault {
        pub owner: Pubkey,

        pub vault_id: u64,

        pub mint: Option<Pubkey>,

        pub last_checkin: i64,

        pub timeout_seconds: i64,

        pub beneficiaries: [Beneficiary; 5],

        pub beneficiary_count: u8,

        pub is_claimed: bool,

        pub claim_pool: u64,

        pub bump: u8,
    }

    impl Vault {
        pub fn new(
            owner: Pubkey,

            vault_id: u64,

            mint: Option<Pubkey>,

            last_checkin: i64,

            timeout_seconds: i64,

            beneficiaries: [Beneficiary; 5],

            beneficiary_count: u8,

            is_claimed: bool,

            claim_pool: u64,

            bump: u8,
        ) -> Self {
            Self {
                owner,

                vault_id,

                mint,

                last_checkin,

                timeout_seconds,

                beneficiaries,

                beneficiary_count,

                is_claimed,

                claim_pool,

                bump,
            }
        }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
